[options]
db_host = localhost
db_port = 5432
db_user = loidd
db_password = loidd
addons_path = E:\odoo train\odoo18\addons, E:\odoo train\odoo18\training
admin_password = loidd
db_name = loidd_odoo18
http_port = 8069
logfile = E:\odoo train\odoo18\odoo.log
admin_passwd = $pbkdf2-sha512$600000$PQeg9D7nvLcWojQGYCxlzA$lUbSIkUvhvPP6ldp/QUv4VbyGH8ekQChPYHUydzU9oXXfaefcyiqZW7bHJJ.ZUgymWaB5a3P8akvsjeJCt1Mog

